# Generated by Django 6.0.8 on 2026-10-02 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='activation_link_expiry_hours',
            field=models.PositiveIntegerField(default=24),
        ),
    ]
