from django.urls import path

from .views import (
    EmployeeCreateAPIView,
    OnboardingCorrectionRequestCreateAPIView,
    StartOnboardingAPIView,
    SubmitOnboardingAPIView,
    StartOnboardingCorrectionsAPIView,
    ResubmitOnboardingAPIView,
    VerifyOnboardingCorrectionAPIView,
    ResolveOnboardingCorrectionItemAPIView,
    ApproveOnboardingAPIView,
    VerifyEmployeeActivationTokenAPIView,
    ResendEmployeeActivationAPIView,
    RequestEmployeeActivationOTPAPIView,
    VerifyEmployeeActivationOTPAPIView,
    SetEmployeeActivationPasswordAPIView,
    EmployeeOnboardingDetailsAPIView,
    EmployeeOnboardingDocumentsAPIView,
    VerifyEmployeeDocumentAPIView,
)


urlpatterns = [
    path(
        "create/",
        EmployeeCreateAPIView.as_view(),
        name="employee-create",
    ),
    path(
        "corrections/create/",
        OnboardingCorrectionRequestCreateAPIView.as_view(),
        name="onboarding-correction-create",
    ),
    path(
    "onboarding/details/",
    EmployeeOnboardingDetailsAPIView.as_view(),
    name="employee-onboarding-details",
    ),
    path(
    "onboarding/documents/",
    EmployeeOnboardingDocumentsAPIView.as_view(),
    name="employee-onboarding-documents",
    ),
    path(
    "onboarding/documents/verify/",
    VerifyEmployeeDocumentAPIView.as_view(),
    name="employee-onboarding-document-verify",
    ),
    path(
    "onboarding/start/",
    StartOnboardingAPIView.as_view(),
    name="onboarding-start",
    ),
    path(
    "onboarding/submit/",
    SubmitOnboardingAPIView.as_view(),
    name="onboarding-submit",
    ),
    path(
    "corrections/start/",
    StartOnboardingCorrectionsAPIView.as_view(),
    name="onboarding-corrections-start",
    ),
    path(
    "onboarding/resubmit/",
    ResubmitOnboardingAPIView.as_view(),
    name="onboarding-resubmit",
    ),
    path(
    "corrections/items/resolve/",
    ResolveOnboardingCorrectionItemAPIView.as_view(),
    name="onboarding-correction-item-resolve",
    ),
    path(
    "activation/otp/request/",
    RequestEmployeeActivationOTPAPIView.as_view(),
    name="employee-activation-otp-request",
    ),
    path(
    "activation/password/set/",
    SetEmployeeActivationPasswordAPIView.as_view(),
    name="employee-activation-password-set",
    ),
    path(
    "activation/otp/verify/",
    VerifyEmployeeActivationOTPAPIView.as_view(),
    name="employee-activation-otp-verify",
    ),
    path(
    "activation/resend/",
    ResendEmployeeActivationAPIView.as_view(),
    name="employee-activation-resend",
    ),
    path(
    "activation/verify/",
    VerifyEmployeeActivationTokenAPIView.as_view(),
    name="employee-activation-verify",
    ),
    path(
    "onboarding/approve/",
    ApproveOnboardingAPIView.as_view(),
    name="onboarding-approve",
    ),
    path(
    "corrections/verify/",
    VerifyOnboardingCorrectionAPIView.as_view(),
    name="onboarding-correction-verify",
    ),
]