# Generated by Django 6.0.8 on 2026-08-22 05:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employee',
            name='probation_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('PENDING_ONBOARDING', 'Pending Onboarding'), ('ONBOARDING_IN_PROGRESS', 'Onboarding In Progress'), ('ONBOARDING_SUBMITTED', 'Onboarding Submitted'), ('CHANGES_REQUIRED', 'Changes Required'), ('PENDING_APPROVAL', 'Pending Approval'), ('ACTIVE', 'Active'), ('DEACTIVATED', 'Deactivated')], default='PENDING_ONBOARDING', max_length=30),
        ),
    ]
