# Generated by Django 6.0.8 on 2026-09-01 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_alter_employee_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='onboarding_reference',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
