# Generated by Django 6.0.8 on 2026-09-06 05:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_onboardingreferencesequence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(choices=[('PENDING_ONBOARDING', 'Pending Onboarding'), ('ONBOARDING_IN_PROGRESS', 'Onboarding In Progress'), ('ONBOARDING_SUBMITTED', 'Onboarding Submitted'), ('CHANGES_REQUIRED', 'Changes Required'), ('PENDING_APPROVAL', 'Pending Approval'), ('REJECTED', 'Rejected'), ('ACTIVE', 'Active'), ('DEACTIVATED', 'Deactivated')], default='PENDING_ONBOARDING', max_length=30),
        ),
        migrations.CreateModel(
            name='OnboardingCorrectionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('PENDING_VERIFICATION', 'Pending Verification'), ('RESOLVED', 'Resolved')], default='OPEN', max_length=30)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='onboarding_correction_requests', to='employees.employee')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='onboarding_correction_requests_created', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='onboarding_correction_requests_resolved', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OnboardingCorrectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('INFORMATION', 'Information'), ('DOCUMENT', 'Document')], max_length=20)),
                ('field_name', models.CharField(max_length=100)),
                ('instruction', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RESOLVED', 'Resolved')], default='PENDING', max_length=20)),
                ('correction_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='employees.onboardingcorrectionrequest')),
            ],
        ),
    ]
