# Generated by Django 6.0.8 on 2026-10-04 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0012_employeeactivationtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeActivationOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('MOBILE', 'Mobile')], default='EMAIL', max_length=20)),
                ('code_hash', models.CharField(max_length=128)),
                ('expires_at', models.DateTimeField()),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('invalidated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activation_token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otp_records', to='employees.employeeactivationtoken')),
            ],
        ),
    ]
