# Generated by Django 6.0.8 on 2026-10-06 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_documentrequirement'),
        ('employees', '0014_employeeonboardingdetails'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='employee_documents/%Y/%m/')),
                ('status', models.CharField(choices=[('PENDING_VERIFICATION', 'Pending Verification'), ('VERIFIED', 'Verified'), ('CHANGES_REQUIRED', 'Changes Required')], default='PENDING_VERIFICATION', max_length=30)),
                ('remarks', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_requirement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_documents', to='accounts.documentrequirement')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='employees.employee')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_documents_uploaded', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_documents_verified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['document_requirement__name'],
                'constraints': [models.UniqueConstraint(fields=('employee', 'document_requirement'), name='one_current_document_per_requirement')],
            },
        ),
    ]
